site_name: Detran-DF
theme:
  name: 'material'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade:
    - Rich Picture: prerastreabilidade/richPicture/richpicture.md
  - Elicitação:
    - Técnicas:
      - Brainstorm: 'elicitação/brainstorm.md'
      - Introspecção: 'elicitação/introspeccao.md'
      - Questionário: 'elicitação/questionario.md'
      - Personas: 'elicitação/persona.md'
    - Priorização: 'elicitação/priorização/moscow.md'
    - Resultado: 'elicitação/resultado.md'
  - Apresentações: 'apresentacoes.md'
