site_name: Detran-DF
theme:
  name: 'material'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade:
    - Rich Picture: prerastreabilidade/richPicture/richpicture.md
  - Elicitação:
    - Técnicas:
      - Introspecção: 'elicitação/introspeccao.md'
      - Questionário: 'elicitação/questionario.md'
      - Personas: 'elicitação/persona.md'
      
