site_name: Detran-DF
theme:
  name: 'material'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade:
    - Rich Picture: prerastreabilidade/richPicture/richpicture.md
  - Elicitação:
    - Técnicas:
      - Brainstorm: 'elicitação/brainstorm.md'
      - Introspecção: 'elicitação/introspeccao.md'
      - Questionário: 'elicitação/questionario.md'
      - Personas: 'elicitação/persona.md'
    - Resultado: 'elicitação/resultado.md'
    - Priorização: 'elicitação/priorização/moscow.md'
  - Modelagem:
    - Léxicos: 'modelagem/lexico.md'
    - Cenários: 'modelagem/cenarios.md'
    - Casos de Uso: 'modelagem/casos.md'
    - Especificação Suplementar: 'modelagem/especificacao.md'
    - NFR Framework: 'modelagem/nfr.md'
    - Backlog:
      - Backlog do produto: 'modelagem/backlog/backlog.md'
      - EP01 - Conta: 'modelagem/backlog/epConta.md'
      - EP02 - Habilitação: 'modelagem/backlog/epHabilitacao.md'
      - EP03 - Veículo: 'modelagem/backlog/epVeiculo.md'
      - EP04 - Infração: 'modelagem/backlog/epInfracao.md'
      - EP05 - Agendamentos: 'modelagem/backlog/epAgendamento.md'
      - Histórias de Usuários: 'modelagem/historia.md'
  - Design, Avaliação e Desenvolvimento: 
    - Nivel 1:
      - Análise de Tarefas:
        - Planejamento da avaliação de análise de tarefas: 'design-avaliacao-desenvolvimento\nivel1\planejamentoAvaliaçãoAnalisedeTarefas.md'
        - Planejamento do relato dos resultados da análise de tarefas: 'design-avaliacao-desenvolvimento\nivel1\planejamentoResultadoAnalisedeTarefas.md'
      - StoryBoard:
        - Planejamento da avaliação - Storyboard: 'design-avaliacao-desenvolvimento\nivel1\planejamentoAvaliaçãoStoryBoard.md'
        - Planejamento do relato dos resultados do Storyboard: 'design-avaliacao-desenvolvimento\nivel1\planejamentoResultadoStoryBoard.md'
  - Apresentações: 'apresentacoes.md'
