site_name: Detran-DF
theme:
  name: 'material'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastriabilidade:
    - Rich Picture: 'prerastreabilidade/richpicture.md'
  - Apresentação: apresentacoes.md
  # Sempre deixar apresentação por último
