site_name: Detran-DF
theme:
  name: 'material'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade:
    - Rich Picture: prerastreabilidade/richPicture/richpicture.md
  - Elicitação:
    - Técnicas:
      - Brainstorm: 'elicitação/brainstorm.md'
      - Introspecção: 'elicitação/introspeccao.md'
      - Questionário: 'elicitação/questionario.md'
      - Personas: 'elicitação/persona.md'
    - Resultado: 'elicitação/resultado.md'
    - Priorização: 'elicitação/priorização/moscow.md'
  - Modelagem:
    - Léxicos: 'modelagem/lexico.md'
    - Cenários: 'modelagem/cenarios.md'
    - Casos de Uso: 'modelagem/casos.md'
    - Especificação Suplementar: 'modelagem/especificacao.md'
    - NFR Framework: 'modelagem/nfr.md'
    - Backlog:
      - Backlog do produto: 'modelagem/backlog/backlog.md'
      - EP01 - Conta: 'modelagem/backlog/epConta.md'
      - EP02 - Habilitação: 'modelagem/backlog/epHabilitacao.md'
      - EP03 - Veículo: 'modelagem/backlog/epVeiculo.md'
      - EP04 - Infração: 'modelagem/backlog/epInfracao.md'
      - EP05 - Agendamentos: 'modelagem/backlog/epAgendamento.md'
      - Histórias de Usuários: 'modelagem/historia.md'
  - Análise:
    - Verificação:
      - Planejamento: analise/verificacao/planejamento.md
      - Rich Picture: analise/verificacao/rich_picture.md
      - Brainstorm: analise/verificacao/brainstorm.md
      - Introspecção: analise/verificacao/introspeccao.md
      - Questionário: analise/verificacao/questionario.md
      - Personas: analise/verificacao/persona.md
      - Priorização: analise/verificacao/moscow.md
      - Léxicos: analise/verificacao/lexicos.md
      - Cenários: analise/verificacao/cenarios.md
      - Casos de Uso: analise/verificacao/casos_de_uso.md
      - Especificação Suplementar: analise/verificacao/esp_suplementar.md
      - NFR Framework: analise/verificacao/nfr_framework.md
      - Backlog: analise/verificacao/backlog.md    
    - Validação:
      - Prototipação: analise/validacao/prototipacao.md
      - Validação Informal: analise/validacao/validacao_informal.md
  - Pós-Rastreabilidade:
    - Backward-From: pos_rastreabilidade/backward_from.md
    - Forward-From: pos_rastreabilidade/forward_from.md
  - Apresentações: 'apresentacoes.md'
