site_name: Detran-DF
theme:
  name: 'readthedocs'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade:
    - Rich Picture: prerastreabilidade/richPicture/richpicture.md
  - Elicitação:
    - Priorização: elicitacao/priorizacao/moscow.md
